/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HistoryLazyImport = createFileRoute('/history')()
const VideoIdLazyImport = createFileRoute('/$videoId')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const HistoryLazyRoute = HistoryLazyImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))

const VideoIdLazyRoute = VideoIdLazyImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$videoId.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$videoId': {
      id: '/$videoId'
      path: '/$videoId'
      fullPath: '/$videoId'
      preLoaderRoute: typeof VideoIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$videoId': typeof VideoIdLazyRoute
  '/history': typeof HistoryLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$videoId': typeof VideoIdLazyRoute
  '/history': typeof HistoryLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$videoId': typeof VideoIdLazyRoute
  '/history': typeof HistoryLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$videoId' | '/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$videoId' | '/history'
  id: '__root__' | '/' | '/$videoId' | '/history'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  VideoIdLazyRoute: typeof VideoIdLazyRoute
  HistoryLazyRoute: typeof HistoryLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  VideoIdLazyRoute: VideoIdLazyRoute,
  HistoryLazyRoute: HistoryLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$videoId",
        "/history"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$videoId": {
      "filePath": "$videoId.lazy.tsx"
    },
    "/history": {
      "filePath": "history.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
