codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 50%
      ui:
        paths: ['packages/ui/**']
        target: 20%
      core:
        paths: ['packages/core/**']
        target: 55%
    patch:
      default:
        target: 50%

ignore:
  - 'apps/docs/**/*' # Ignore documentation app
  - '**/types.ts' # Ignore TypeScript interfaces
  - '**/*.stories.tsx' # Ignore Storybook files
  - 'packages/ui/.storybook/**/*' # Ignore Storybook files
  - '**/test/**/*' # Ignore test files
  - '**/*.test.*' # Ignore test files
  - '**/*.spec.*' # Ignore spec files
  - '**/[Ss]tyled*.{ts,tsx}' # Ignore files starting with Styled/styled
  - '**/styled.tsx' # Ignore files starting with Styled/styled
  - '**/texts.ts' # Ignore text constant files
  - 'packages/core/src/graphql/**' # Ignore generated GraphQL file
  - '**/storybook-static/**/*' # Ignore storybook assets
  - '**/vite.config.ts' # ignore config files
  - '**/tsup.config.ts' # ignore config files
  - '**/interface.ts' # ignore TypeScript interfaces
  - '**/fragments.ts' # ignore GraphQL fragments
  - '**/dist/**/*' # Ignore dist folder
  - 'packages/core/src/universal/errors/**/*'

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: false
  require_bundle_changes: 'bundle_increase'
  bundle_change_threshold: '50Kb'
