/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WriteImport } from './routes/write'
import { Route as MenuBarImport } from './routes/menuBar'
import { Route as PostsSlugIdImport } from './routes/posts.$slug.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WriteRoute = WriteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRoute,
} as any)

const MenuBarRoute = MenuBarImport.update({
  id: '/menuBar',
  path: '/menuBar',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PostsSlugIdRoute = PostsSlugIdImport.update({
  id: '/posts/$slug/$id',
  path: '/posts/$slug/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/menuBar': {
      id: '/menuBar'
      path: '/menuBar'
      fullPath: '/menuBar'
      preLoaderRoute: typeof MenuBarImport
      parentRoute: typeof rootRoute
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteImport
      parentRoute: typeof rootRoute
    }
    '/posts/$slug/$id': {
      id: '/posts/$slug/$id'
      path: '/posts/$slug/$id'
      fullPath: '/posts/$slug/$id'
      preLoaderRoute: typeof PostsSlugIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/menuBar': typeof MenuBarRoute
  '/write': typeof WriteRoute
  '/posts/$slug/$id': typeof PostsSlugIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/menuBar': typeof MenuBarRoute
  '/write': typeof WriteRoute
  '/posts/$slug/$id': typeof PostsSlugIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/menuBar': typeof MenuBarRoute
  '/write': typeof WriteRoute
  '/posts/$slug/$id': typeof PostsSlugIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menuBar' | '/write' | '/posts/$slug/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menuBar' | '/write' | '/posts/$slug/$id'
  id: '__root__' | '/' | '/menuBar' | '/write' | '/posts/$slug/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MenuBarRoute: typeof MenuBarRoute
  WriteRoute: typeof WriteRoute
  PostsSlugIdRoute: typeof PostsSlugIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MenuBarRoute: MenuBarRoute,
  WriteRoute: WriteRoute,
  PostsSlugIdRoute: PostsSlugIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/menuBar",
        "/write",
        "/posts/$slug/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/menuBar": {
      "filePath": "menuBar.tsx"
    },
    "/write": {
      "filePath": "write.tsx"
    },
    "/posts/$slug/$id": {
      "filePath": "posts.$slug.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
