-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."videos" add column "skip_process" boolean
--  not null default 'false';
