-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."reading_progresses" add column "reading_time_minutes" integer
--  null default '0';
