-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."shared_video_recipients" add column "recipient_id" uuid
--  null;
