/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')();
const PlaylistsIndexLazyImport = createFileRoute('/playlists/')();
const PlaylistsIdLazyImport = createFileRoute('/playlists/$id')();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));

const PlaylistsIndexLazyRoute = PlaylistsIndexLazyImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/playlists.index.lazy').then((d) => d.Route),
);

const PlaylistsIdLazyRoute = PlaylistsIdLazyImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/playlists.$id.lazy').then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/playlists/$id': {
      id: '/playlists/$id';
      path: '/playlists/$id';
      fullPath: '/playlists/$id';
      preLoaderRoute: typeof PlaylistsIdLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/playlists/': {
      id: '/playlists/';
      path: '/playlists';
      fullPath: '/playlists';
      preLoaderRoute: typeof PlaylistsIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute;
  '/playlists/$id': typeof PlaylistsIdLazyRoute;
  '/playlists': typeof PlaylistsIndexLazyRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute;
  '/playlists/$id': typeof PlaylistsIdLazyRoute;
  '/playlists': typeof PlaylistsIndexLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexLazyRoute;
  '/playlists/$id': typeof PlaylistsIdLazyRoute;
  '/playlists/': typeof PlaylistsIndexLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/playlists/$id' | '/playlists';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/playlists/$id' | '/playlists';
  id: '__root__' | '/' | '/playlists/$id' | '/playlists/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  PlaylistsIdLazyRoute: typeof PlaylistsIdLazyRoute;
  PlaylistsIndexLazyRoute: typeof PlaylistsIndexLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PlaylistsIdLazyRoute: PlaylistsIdLazyRoute,
  PlaylistsIndexLazyRoute: PlaylistsIndexLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/playlists/$id",
        "/playlists/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/playlists/$id": {
      "filePath": "playlists.$id.lazy.tsx"
    },
    "/playlists/": {
      "filePath": "playlists.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
