/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const AlbumAlbumIdLazyRouteImport = createFileRoute('/album/$albumId')()
const PhotoPhotoIdLazyRouteImport = createFileRoute('/photo/$photoId')()
const AlbumAlbumIdPhotoPhotoIdLazyRouteImport = createFileRoute(
  '/album/$albumId_/photo/$photoId',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AlbumAlbumIdLazyRoute = AlbumAlbumIdLazyRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/album.$albumId.lazy').then((d) => d.Route),
)
const PhotoPhotoIdLazyRoute = PhotoPhotoIdLazyRouteImport.update({
  id: '/photo/$photoId',
  path: '/photo/$photoId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/photo.$photoId.lazy').then((d) => d.Route),
)
const AlbumAlbumIdPhotoPhotoIdLazyRoute =
  AlbumAlbumIdPhotoPhotoIdLazyRouteImport.update({
    id: '/album/$albumId_/photo/$photoId',
    path: '/album/$albumId/photo/$photoId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/album.$albumId_.photo.$photoId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/album/$albumId': typeof AlbumAlbumIdLazyRoute
  '/photo/$photoId': typeof PhotoPhotoIdLazyRoute
  '/album/$albumId/photo/$photoId': typeof AlbumAlbumIdPhotoPhotoIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/album/$albumId': typeof AlbumAlbumIdLazyRoute
  '/photo/$photoId': typeof PhotoPhotoIdLazyRoute
  '/album/$albumId/photo/$photoId': typeof AlbumAlbumIdPhotoPhotoIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/album/$albumId': typeof AlbumAlbumIdLazyRoute
  '/photo/$photoId': typeof PhotoPhotoIdLazyRoute
  '/album/$albumId_/photo/$photoId': typeof AlbumAlbumIdPhotoPhotoIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album/$albumId'
    | '/photo/$photoId'
    | '/album/$albumId/photo/$photoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album/$albumId'
    | '/photo/$photoId'
    | '/album/$albumId/photo/$photoId'
  id:
    | '__root__'
    | '/'
    | '/album/$albumId'
    | '/photo/$photoId'
    | '/album/$albumId_/photo/$photoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AlbumAlbumIdLazyRoute: typeof AlbumAlbumIdLazyRoute
  PhotoPhotoIdLazyRoute: typeof PhotoPhotoIdLazyRoute
  AlbumAlbumIdPhotoPhotoIdLazyRoute: typeof AlbumAlbumIdPhotoPhotoIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$photoId': {
      id: '/photo/$photoId'
      path: '/photo/$photoId'
      fullPath: '/photo/$photoId'
      preLoaderRoute: typeof PhotoPhotoIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId_/photo/$photoId': {
      id: '/album/$albumId_/photo/$photoId'
      path: '/album/$albumId/photo/$photoId'
      fullPath: '/album/$albumId/photo/$photoId'
      preLoaderRoute: typeof AlbumAlbumIdPhotoPhotoIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AlbumAlbumIdLazyRoute: AlbumAlbumIdLazyRoute,
  PhotoPhotoIdLazyRoute: PhotoPhotoIdLazyRoute,
  AlbumAlbumIdPhotoPhotoIdLazyRoute: AlbumAlbumIdPhotoPhotoIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
