import { SEVERITY } from './severity';
import type { ErrorMap } from './types';

/**
 * Reference
 * https://github.com/hasura/graphql-engine/blob/master/server/lib/hasura-base/src/Hasura/Base/Error.hs
 *
 * The only case that can be retried is timeout
 */
const HASURA_NATIVE_ERROR_CODES = {
  ACCESSDENIED: 'access-denied',
  ALREADYEXISTS: 'already-exists',
  ALREADYTRACKED: 'already-tracked',
  ALREADYUNTRACKED: 'already-untracked',
  BADREQUEST: 'bad-request',
  BIGQUERYERROR: 'bigquery-error',
  BUSY: 'busy',
  CONCURRENTUPDATE: 'concurrent-update',
  CONNECTIONNOTESTABLISHED: 'connection-not-established',
  COERCIONERROR: 'coercion-error',
  CONFLICT: 'conflict',
  CONSTRAINTERROR: 'constraint-error',
  CONSTRAINTVIOLATION: 'constraint-violation',
  CYCLICDEPENDENCY: 'cyclic-dependency',
  DATAEXCEPTION: 'data-exception',
  DATACONNECTORERROR: 'data-connector-error',
  DEPENDENCYERROR: 'dependency-error',
  INVALIDCONFIGURATION: 'invalid-configuration',
  INVALIDHEADERS: 'invalid-headers',
  INVALIDJSON: 'invalid-json',
  INVALIDPARAMS: 'invalid-params',
  JWTINVALID: 'invalid-jwt',
  JWTINVALIDCLAIMS: 'jwt-invalid-claims',
  JWTROLECLAIMMISSING: 'jwt-missing-role-claims',
  MSSQLERROR: 'mssql-error',
  METHODNOTALLOWED: 'method-not-allowed',
  NOTEXISTS: 'not-exists',
  NOTFOUND: 'not-found',
  NOTSUPPORTED: 'not-supported',
  PARSEFAILED: 'parse-failed',
  PERMISSIONDENIED: 'permission-denied',
  PERMISSIONERROR: 'permission-error',
  POSTGRESERROR: 'postgres-error',
  POSTGRESMAXCONNECTIONSERROR: 'postgres-max-connections-error',
  REMOTESCHEMACONFLICTS: 'remote-schema-conflicts',
  REMOTESCHEMAERROR: 'remote-schema-error',
  STARTFAILED: 'start-failed',
  UNEXPECTED: 'unexpected',
  UNEXPECTEDPAYLOAD: 'unexpected-payload',
  VALIDATIONFAILED: 'validation-failed',
  TEMPLATERESOLUTIONFAILED: 'template-resolution-failed',
  TIMEOUTERRORCODE: 'timeout',
} as const;

const HASURA_NATIVE_ERRORS: ErrorMap<typeof HASURA_NATIVE_ERROR_CODES> = {
  [HASURA_NATIVE_ERROR_CODES.ACCESSDENIED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage:
      'Access denied. You do not have permission to perform this action.',
  },
  [HASURA_NATIVE_ERROR_CODES.ALREADYEXISTS]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'This resource already exists.',
  },
  [HASURA_NATIVE_ERROR_CODES.ALREADYTRACKED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'This resource is already being tracked.',
  },
  [HASURA_NATIVE_ERROR_CODES.ALREADYUNTRACKED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'This resource is not currently tracked.',
  },
  [HASURA_NATIVE_ERROR_CODES.BADREQUEST]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Invalid request. Please check your input and try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.BIGQUERYERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Database query error. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.BUSY]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Service is busy. Please try again in a moment.',
  },
  [HASURA_NATIVE_ERROR_CODES.CONCURRENTUPDATE]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Another update is in progress. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.CONNECTIONNOTESTABLISHED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.HIGH,
    userMessage: 'Database connection error. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.COERCIONERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Data type error. Please check your input format.',
  },
  [HASURA_NATIVE_ERROR_CODES.CONFLICT]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Data conflict detected. Please refresh and try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.CONSTRAINTERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Data constraint violation. Please check your input.',
  },
  [HASURA_NATIVE_ERROR_CODES.CONSTRAINTVIOLATION]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Data validation failed. Please check your input.',
  },
  [HASURA_NATIVE_ERROR_CODES.CYCLICDEPENDENCY]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Circular dependency detected in your data.',
  },
  [HASURA_NATIVE_ERROR_CODES.DATAEXCEPTION]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Data processing error. Please check your input.',
  },
  [HASURA_NATIVE_ERROR_CODES.DATACONNECTORERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.HIGH,
    userMessage: 'Database connection error. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.DEPENDENCYERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Dependency error. Please check related data.',
  },
  [HASURA_NATIVE_ERROR_CODES.INVALIDCONFIGURATION]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.HIGH,
    userMessage: 'Service configuration error. Please try again later.',
  },
  [HASURA_NATIVE_ERROR_CODES.INVALIDHEADERS]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Invalid request headers. Please refresh and try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.INVALIDJSON]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Invalid data format. Please check your input.',
  },
  [HASURA_NATIVE_ERROR_CODES.INVALIDPARAMS]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Invalid parameters. Please check your input.',
  },
  [HASURA_NATIVE_ERROR_CODES.JWTINVALID]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Authentication failed. Please sign in again.',
  },
  [HASURA_NATIVE_ERROR_CODES.JWTINVALIDCLAIMS]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Invalid authentication token. Please sign in again.',
  },
  [HASURA_NATIVE_ERROR_CODES.JWTROLECLAIMMISSING]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Authentication error. Please sign in again.',
  },
  [HASURA_NATIVE_ERROR_CODES.MSSQLERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Database error. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.METHODNOTALLOWED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'This operation is not allowed.',
  },
  [HASURA_NATIVE_ERROR_CODES.NOTEXISTS]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'The requested resource does not exist.',
  },
  [HASURA_NATIVE_ERROR_CODES.NOTFOUND]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'The requested content was not found.',
  },
  [HASURA_NATIVE_ERROR_CODES.NOTSUPPORTED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'This operation is not supported.',
  },
  [HASURA_NATIVE_ERROR_CODES.PARSEFAILED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Failed to parse your request. Please check the format.',
  },
  [HASURA_NATIVE_ERROR_CODES.PERMISSIONDENIED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Permission denied. You do not have access to this resource.',
  },
  [HASURA_NATIVE_ERROR_CODES.PERMISSIONERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Permission error. Please check your access rights.',
  },
  [HASURA_NATIVE_ERROR_CODES.POSTGRESERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Database error. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.POSTGRESMAXCONNECTIONSERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.HIGH,
    userMessage: 'Database is busy. Please try again in a moment.',
  },
  [HASURA_NATIVE_ERROR_CODES.REMOTESCHEMACONFLICTS]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Schema conflict detected. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.REMOTESCHEMAERROR]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Remote service error. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.STARTFAILED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.HIGH,
    userMessage: 'Service startup failed. Please try again later.',
  },
  [HASURA_NATIVE_ERROR_CODES.UNEXPECTED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.HIGH,
    userMessage: 'An unexpected error occurred. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.UNEXPECTEDPAYLOAD]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Unexpected data format received. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.VALIDATIONFAILED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.LOW,
    userMessage: 'Data validation failed. Please check your input.',
  },
  [HASURA_NATIVE_ERROR_CODES.TEMPLATERESOLUTIONFAILED]: {
    shouldAlert: false,
    shouldRetry: false,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Template processing failed. Please try again.',
  },
  [HASURA_NATIVE_ERROR_CODES.TIMEOUTERRORCODE]: {
    shouldAlert: false,
    shouldRetry: true,
    severity: SEVERITY.MEDIUM,
    userMessage: 'Request timed out. Please try again.',
  },
};

export { HASURA_NATIVE_ERROR_CODES, HASURA_NATIVE_ERRORS };
